name: monobox
description: Fila Flutter mobile app.

publish_to: 'none'

version: 1.0.2+3

environment:
  sdk: '>=3.1.2 <4.0.0'

dependencies:
  adaptive_action_sheet: ^2.0.3
  auto_route: ^7.8.4
  bottom_sheet: ^4.0.0
  cached_network_image: ^3.3.0
  carousel_slider: ^4.2.1
  dadata: ^0.3.3
  decimal: ^2.3.3
  dio: ^5.4.0
  dotted_border: ^2.1.0
  equatable: ^2.0.5
  fast_cached_network_image: ^1.3.3+5
  firebase_core: ^2.24.2
  firebase_crashlytics: ^3.4.19
  firebase_messaging: ^14.7.20
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  flutter_cached_pdfview: ^0.4.2
  flutter_carousel_widget: ^2.3.0
  flutter_launcher_icons: ^0.13.1
  flutter_local_notifications: ^17.2.2
  flutter_localization: ^0.2.0
  flutter_masked_text2: ^0.9.1
  flutter_native_splash: ^2.3.8
  flutter_svg: ^2.0.9
  flutter_typeahead: ^5.0.1
  flutter_widget_from_html: ^0.15.3
  freezed_annotation: ^2.4.1
  geolocator: ^10.1.0
  get_it: ^7.6.4
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  image_picker: ^1.0.4
  intl: ^0.19.0
  json_annotation: ^4.8.1
  logger: ^2.0.2+1
  php_serializer: ^1.1.0
  pinput: ^3.0.1
  pretty_dio_logger: ^1.3.1
  pretty_qr_code: ^3.0.0
  retrofit: ^4.1.0
  scrollable_positioned_list: ^0.3.8
  share_plus: ^9.0.0
  shared_preferences: ^2.2.2
  shimmer: ^3.0.0
  sliding_sheet2: ^2.0.1
  swipeable_tile: ^2.0.0+3
  talker: ^3.2.0
  talker_bloc_logger: ^2.4.0
  talker_dio_logger: ^2.4.0
  timeline_tile: ^2.0.0
  url_launcher: ^6.2.2
  uuid: ^4.2.1
  webview_flutter: ^4.4.2
  yandex_mapkit: ^4.1.0



#dart run build_runner build --delete-conflicting-outputs
dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.1
  retrofit_generator: ^8.1.0
  build_runner: ^2.4.7
  json_serializable: ^6.7.1
  freezed: ^2.4.5
  auto_route_generator: ^7.3.2
  hive_generator: ^2.0.1

flutter_launcher_icons:
  android: "ic_launcher"
  ios: false
  image_path_android: "assets/images/logo/new_logo.png"

flutter:

  uses-material-design: true


  assets:
    - assets/icons/
    - assets/images/

  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto/Roboto-Regular.ttf
          weight: 400
        - asset: assets/fonts/Roboto/Roboto-Thin.ttf
          weight: 100
        - asset: assets/fonts/Roboto/Roboto-Light.ttf
          weight: 300
        - asset: assets/fonts/Roboto/Roboto-Medium.ttf
          weight: 500
        - asset: assets/fonts/Roboto/Roboto-Bold.ttf
          weight: 700
        - asset: assets/fonts/Roboto/Roboto-Black.ttf
          weight: 900
        - asset: assets/fonts/Roboto/Roboto-RegularItalic.ttf
          weight: 400
          style: italic
        - asset: assets/fonts/Roboto/Roboto-ThinItalic.ttf
          weight: 100
          style: italic
        - asset: assets/fonts/Roboto/Roboto-LightItalic.ttf
          weight: 300
          style: italic
        - asset: assets/fonts/Roboto/Roboto-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: assets/fonts/Roboto/Roboto-BoldItalic.ttf
          weight: 700
          style: italic
        - asset: assets/fonts/Roboto/Roboto-BlackItalic.ttf
          weight: 900
          style: italic

